### PR TITLE
adding ability to replace smart quotes with straight quotes

### PR DESCRIPTION
**Pull request by dkelly-sighter**

### CODE REVIEW

**Comment by alexwforsythe** [comment]
Hey, thanks for the PR. Smart quotes are the devil. Let's just replace them without giving an option since they have nothing to do with programming. So:

1. Can you remove the checkbox and conditional so it always replaces special chars
2. Please move `performReplaceSmartQuotes` to the beginning of `createHighlightedBlock` so that the preview accurately reflects the replacement

**Comment by dkelly-sighter** [comment]
Love it. Will update!

**Comment by dkelly-sighter** [comment]
Took awhile, but here's the requested.

**Comment by alexwforsythe** [comment]
Thanks! Sorry for taking so long.

**Pull request merged**
